var stations = [
    {
        "id": 80,
        "borough": "Brooklyn",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Elevated Mezzanine",
        "platform_type": "Sides",
        "package": "Package 1",
        "lines": [],
        "task_id": 2,
        "station_name": "Prospect Avenue",
        "station_id": "BK1",
        "latitude": 40.666789,
        "longitude": -73.994079,
        "is_historic_landmark": false,
        "area_square_feet": 33000.0,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 2,
        "track_comments": "Full curtain wall separating the two outer local and two middle express tracks.",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": true,
        "has_street_entrance": false,
        "subway_division": 25
    },
    {
        "id": 81,
        "borough": "Brooklyn",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Elevated Mezzanine",
        "platform_type": "Sides",
        "package": "Package 1",
        "lines": [],
        "task_id": 2,
        "station_name": "Bay Ridge Avenue",
        "station_id": "BK2",
        "latitude": 40.633678,
        "longitude": -74.023853,
        "is_historic_landmark": false,
        "area_square_feet": 39758.0,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 0,
        "track_comments": "",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": true,
        "has_street_entrance": false,
        "subway_division": 25
    },
    {
        "id": 82,
        "borough": "Brooklyn",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Elevated Mezzanine",
        "platform_type": "Sides",
        "package": "Package 1",
        "lines": [],
        "task_id": 2,
        "station_name": "53rd Street",
        "station_id": "BK3",
        "latitude": 40.643611,
        "longitude": -74.015517,
        "is_historic_landmark": false,
        "area_square_feet": 52356.799999999996,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 2,
        "track_comments": "Two outer local tracks and two middle express tracks",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": true,
        "has_street_entrance": false,
        "subway_division": 25
    },
    {
        "id": 83,
        "borough": "Brooklyn",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Double Loaded Mezzanine",
        "platform_type": "Sides",
        "package": "Package 8",
        "lines": [],
        "task_id": 2,
        "station_name": "Flushing Avenue",
        "station_id": "BK4",
        "latitude": 40.70026,
        "longitude": -73.941126,
        "is_historic_landmark": false,
        "area_square_feet": 47935.8,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 0,
        "track_comments": "",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": false,
        "has_street_entrance": true,
        "subway_division": 26
    },
    {
        "id": 84,
        "borough": "Brooklyn",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "No Mezzanine",
        "platform_type": "Sides",
        "package": "Package 8",
        "lines": [],
        "task_id": 2,
        "station_name": "Classon Avenue",
        "station_id": "BK5",
        "latitude": 40.688873,
        "longitude": -73.96007,
        "is_historic_landmark": false,
        "area_square_feet": 67000.1,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 0,
        "track_comments": "",
        "has_building_entrance": false,
        "has_canopy_entrance": true,
        "has_elevated_entrance": false,
        "has_street_entrance": false,
        "subway_division": 26
    },
    {
        "id": 85,
        "borough": "Brooklyn",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Elevated Mezzanine",
        "platform_type": "Sides",
        "package": "Package 8",
        "lines": [],
        "task_id": 2,
        "station_name": "Clinton & Washington",
        "station_id": "BK6",
        "latitude": 40.688089,
        "longitude": -73.966839,
        "is_historic_landmark": false,
        "area_square_feet": 64679.5,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 2,
        "track_comments": "",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": false,
        "has_street_entrance": true,
        "subway_division": 26
    },
    {
        "id": 86,
        "borough": "Brooklyn",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Elevated Mezzanine",
        "platform_type": "Sides",
        "package": "Package 8",
        "lines": [],
        "task_id": 2,
        "station_name": "Van Siclen Ave",
        "station_id": "BK7",
        "latitude": 40.665449,
        "longitude": -73.889395,
        "is_historic_landmark": false,
        "area_square_feet": 62101.560000000005,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 2,
        "track_comments": "Two outer local tracks and two middle express tracks",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": true,
        "has_street_entrance": false,
        "subway_division": 26
    },
    {
        "id": 87,
        "borough": "Brooklyn",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Elevated Mezzanine",
        "platform_type": "Sides",
        "package": "Package 8",
        "lines": [],
        "task_id": 2,
        "station_name": "Kingston-Throop",
        "station_id": "BK8",
        "latitude": 40.679921,
        "longitude": -73.940858,
        "is_historic_landmark": false,
        "area_square_feet": 73591.5,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 2,
        "track_comments": "Two outer local tracks and two middle express tracks",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": true,
        "has_street_entrance": false,
        "subway_division": 26
    },
    {
        "id": 88,
        "borough": "The Bronx",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Central Large Mezzanine",
        "platform_type": "Sides",
        "package": "Package 5",
        "lines": [],
        "task_id": 2,
        "station_name": "174-175th Streets",
        "station_id": "BX1",
        "latitude": 40.8459,
        "longitude": -73.910136,
        "is_historic_landmark": false,
        "area_square_feet": 90212.0,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 1,
        "track_comments": "Two outer local tracks and an middle express track.",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": false,
        "has_street_entrance": true,
        "subway_division": 26
    },
    {
        "id": 89,
        "borough": "The Bronx",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "No Mezzanine",
        "platform_type": "Sides",
        "package": "Package 5",
        "lines": [],
        "task_id": 2,
        "station_name": "167th Street",
        "station_id": "BX2",
        "latitude": 40.833769,
        "longitude": -73.918432,
        "is_historic_landmark": false,
        "area_square_feet": 71400.8,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 1,
        "track_comments": "Two outer local tracks and an middle express track.",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": false,
        "has_street_entrance": true,
        "subway_division": 26
    },
    {
        "id": 90,
        "borough": "The Bronx",
        "construction_type": "Elevated",
        "mezzanine_configuration": "Elevated Mezzanine",
        "platform_type": "Sides",
        "package": "Package 6",
        "lines": [],
        "task_id": 2,
        "station_name": "Westchester Square",
        "station_id": "BX3",
        "latitude": 40.839892,
        "longitude": -73.842952,
        "is_historic_landmark": true,
        "area_square_feet": 40710.0,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 1,
        "track_comments": "The center track is not used in regular service.",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": true,
        "has_street_entrance": false,
        "subway_division": 27
    },
    {
        "id": 91,
        "borough": "The Bronx",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "No Mezzanine",
        "platform_type": "Island",
        "package": "Package 5",
        "lines": [],
        "task_id": 2,
        "station_name": "138th Street - 3rd Ave.",
        "station_id": "BX4",
        "latitude": 40.810476,
        "longitude": -73.926138,
        "is_historic_landmark": false,
        "area_square_feet": 64287.0,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 1,
        "track_comments": "The center track used for weekday peak direction express service.",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": false,
        "has_street_entrance": true,
        "subway_division": 26
    },
    {
        "id": 92,
        "borough": "The Bronx",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Central Large Mezzanine",
        "platform_type": "Sides",
        "package": "Package 5",
        "lines": [],
        "task_id": 2,
        "station_name": "Brook Avenue",
        "station_id": "BX5",
        "latitude": 40.807566,
        "longitude": -73.91924,
        "is_historic_landmark": false,
        "area_square_feet": 40280.0,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 1,
        "track_comments": "",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": false,
        "has_street_entrance": true,
        "subway_division": 26
    },
    {
        "id": 93,
        "borough": "The Bronx",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Double Loaded Mezzanine",
        "platform_type": "Island",
        "package": "Package 6",
        "lines": [],
        "task_id": 2,
        "station_name": "Hunts Point Avenue",
        "station_id": "BX6",
        "latitude": 40.820948,
        "longitude": -73.890549,
        "is_historic_landmark": false,
        "area_square_feet": 56121.200000000004,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 1,
        "track_comments": "",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": false,
        "has_street_entrance": true,
        "subway_division": 27
    },
    {
        "id": 94,
        "borough": "The Bronx",
        "construction_type": "Open Cut",
        "mezzanine_configuration": "Elevated Mezzanine",
        "platform_type": "Island",
        "package": "Package 6",
        "lines": [],
        "task_id": 2,
        "station_name": "Pelham Parkway",
        "station_id": "BX7",
        "latitude": 40.857192,
        "longitude": -73.867615,
        "is_historic_landmark": false,
        "area_square_feet": 49800.0,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 2,
        "track_comments": "",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": true,
        "has_street_entrance": false,
        "subway_division": 27
    },
    {
        "id": 95,
        "borough": "Manhattan",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Front Loaded Mezzanine",
        "platform_type": "Sides",
        "package": "Package 2",
        "lines": [],
        "task_id": 2,
        "station_name": "163rd Street - Amsterdam Ave.",
        "station_id": "M1",
        "latitude": 40.836013,
        "longitude": -73.939892,
        "is_historic_landmark": false,
        "area_square_feet": 63849.0,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 2,
        "track_comments": "Two local tracks. Two express tracks, used by the A train during daytime hours, run below the station and are not visible from the platforms.",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": false,
        "has_street_entrance": true,
        "subway_division": 26
    },
    {
        "id": 96,
        "borough": "Manhattan",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "No Mezzanine",
        "platform_type": "Sides",
        "package": "Package 2",
        "lines": [],
        "task_id": 2,
        "station_name": "Cathedral Parkway (110th St)",
        "station_id": "M2",
        "latitude": 40.800605,
        "longitude": -73.958158,
        "is_historic_landmark": false,
        "area_square_feet": 68244.0,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 2,
        "track_comments": "",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": false,
        "has_street_entrance": true,
        "subway_division": 26
    },
    {
        "id": 97,
        "borough": "Manhattan",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Central Mezzanine",
        "platform_type": "Stacked Sides",
        "package": "Package 2",
        "lines": [],
        "task_id": 2,
        "station_name": "86th Street",
        "station_id": "M3",
        "latitude": 40.785868,
        "longitude": -73.968916,
        "is_historic_landmark": false,
        "area_square_feet": 72230.0,
        "number_of_platforms": 1,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 2,
        "track_comments": "It has two levels. From west to east, each level has one side platform, one local track and one express track.",
        "has_building_entrance": false,
        "has_canopy_entrance": true,
        "has_elevated_entrance": false,
        "has_street_entrance": false,
        "subway_division": 26
    },
    {
        "id": 98,
        "borough": "Manhattan",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Double Loaded Mezzanine",
        "platform_type": "Stacked Sides",
        "package": "Package 2",
        "lines": [],
        "task_id": 2,
        "station_name": "72nd Street",
        "station_id": "M4",
        "latitude": 40.775594,
        "longitude": -73.97641,
        "is_historic_landmark": false,
        "area_square_feet": 68448.0,
        "number_of_platforms": 1,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 2,
        "track_comments": "It has two levels.  Each level has one local track and one express track. ",
        "has_building_entrance": false,
        "has_canopy_entrance": true,
        "has_elevated_entrance": false,
        "has_street_entrance": true,
        "subway_division": 26
    },
    {
        "id": 99,
        "borough": "Manhattan",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Half / Half",
        "platform_type": "Sides",
        "package": "Package 4",
        "lines": [],
        "task_id": 2,
        "station_name": "23rd Street",
        "station_id": "M5",
        "latitude": 40.742878,
        "longitude": -73.992821,
        "is_historic_landmark": false,
        "area_square_feet": 83539.0,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 0,
        "track_comments": "",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": false,
        "has_street_entrance": true,
        "subway_division": 26
    },
    {
        "id": 100,
        "borough": "Manhattan",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Double Loaded Mezzanine",
        "platform_type": "Island",
        "package": "Package 4",
        "lines": [],
        "task_id": 2,
        "station_name": "57th Street",
        "station_id": "M6",
        "latitude": 40.763972,
        "longitude": -73.97745,
        "is_historic_landmark": false,
        "area_square_feet": 69483.0,
        "number_of_platforms": 1,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 0,
        "track_comments": "",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": false,
        "has_street_entrance": true,
        "subway_division": 26
    },
    {
        "id": 101,
        "borough": "Manhattan",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Half / Half",
        "platform_type": "Sides",
        "package": "Package 5",
        "lines": [],
        "task_id": 2,
        "station_name": "145th Street",
        "station_id": "M7",
        "latitude": 40.820421,
        "longitude": -73.936245,
        "is_historic_landmark": true,
        "area_square_feet": 27730.0,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 0,
        "track_comments": "",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": false,
        "has_street_entrance": true,
        "subway_division": 26
    },
    {
        "id": 102,
        "borough": "Manhattan",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Half / Half",
        "platform_type": "Sides",
        "package": "Package 4",
        "lines": [],
        "task_id": 2,
        "station_name": "28th Street",
        "station_id": "M8",
        "latitude": 40.74307,
        "longitude": -73.984264,
        "is_historic_landmark": false,
        "area_square_feet": 60656.0,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 2,
        "track_comments": "The two middle express tracks run at a lower level than the two outer local ones",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": false,
        "has_street_entrance": true,
        "subway_division": 27
    },
    {
        "id": 103,
        "borough": "Queens",
        "construction_type": "Elevated",
        "mezzanine_configuration": "Central Mezzanine",
        "platform_type": "Sides",
        "package": "Package 3",
        "lines": [],
        "task_id": 2,
        "station_name": "Grand Ave - 30th Ave",
        "station_id": "Q1",
        "latitude": 40.766779,
        "longitude": -73.921479,
        "is_historic_landmark": false,
        "area_square_feet": 52147.5,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 1,
        "track_comments": "The center track is not used in revenue service after 2002.",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": false,
        "has_street_entrance": true,
        "subway_division": 25
    },
    {
        "id": 104,
        "borough": "Queens",
        "construction_type": "Elevated",
        "mezzanine_configuration": "Central Large Mezzanine",
        "platform_type": "Sides",
        "package": "Package 3",
        "lines": [],
        "task_id": 2,
        "station_name": "Broadway",
        "station_id": "Q2",
        "latitude": 40.76182,
        "longitude": -73.925508,
        "is_historic_landmark": false,
        "area_square_feet": 53825.1,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 1,
        "track_comments": "The center track is not used in revenue service after 2002.",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": false,
        "has_street_entrance": true,
        "subway_division": 25
    },
    {
        "id": 105,
        "borough": "Queens",
        "construction_type": "Elevated",
        "mezzanine_configuration": "Elevated Mezzanine",
        "platform_type": "Sides",
        "package": "Package 3",
        "lines": [],
        "task_id": 2,
        "station_name": "Washington Ave - 36th Ave",
        "station_id": "Q3",
        "latitude": 40.756804,
        "longitude": -73.929575,
        "is_historic_landmark": false,
        "area_square_feet": 45981.0,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 1,
        "track_comments": "The center track is not used in revenue service after 2002.",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": true,
        "has_street_entrance": false,
        "subway_division": 25
    },
    {
        "id": 106,
        "borough": "Queens",
        "construction_type": "Elevated",
        "mezzanine_configuration": "Elevated Mezzanine",
        "platform_type": "Sides",
        "package": "Package 3",
        "lines": [],
        "task_id": 2,
        "station_name": "Beebe Ave - 39th Ave",
        "station_id": "Q4",
        "latitude": 40.752882,
        "longitude": -73.932755,
        "is_historic_landmark": false,
        "area_square_feet": 51129.0,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 1,
        "track_comments": "The center track is not used in revenue service after 2002.",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": true,
        "has_street_entrance": false,
        "subway_division": 25
    },
    {
        "id": 107,
        "borough": "Queens",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Elevated Mezzanine",
        "platform_type": "Island",
        "package": "Package 7",
        "lines": [],
        "task_id": 2,
        "station_name": "Parsons Blvd.",
        "station_id": "Q5",
        "latitude": 40.707564,
        "longitude": -73.803326,
        "is_historic_landmark": false,
        "area_square_feet": 126000.0,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 2,
        "track_comments": "Two outer local tracks and two middle express tracks.",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": true,
        "has_street_entrance": false,
        "subway_division": 26
    },
    {
        "id": 108,
        "borough": "Queens",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "No Mezzanine",
        "platform_type": "Sides",
        "package": "Package 7",
        "lines": [],
        "task_id": 2,
        "station_name": "67th Avenue",
        "station_id": "Q6",
        "latitude": 40.726523,
        "longitude": -73.852719,
        "is_historic_landmark": false,
        "area_square_feet": 112320.0,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 2,
        "track_comments": "Two outer local tracks and two middle express tracks.",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": false,
        "has_street_entrance": true,
        "subway_division": 26
    },
    {
        "id": 109,
        "borough": "Queens",
        "construction_type": "Cut and Cover",
        "mezzanine_configuration": "Elevated Mezzanine",
        "platform_type": "Sides",
        "package": "Package 7",
        "lines": [],
        "task_id": 2,
        "station_name": "Northern Blvd.",
        "station_id": "Q7",
        "latitude": 40.752885,
        "longitude": -73.906006,
        "is_historic_landmark": false,
        "area_square_feet": 78480.0,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 0,
        "track_comments": " The express tracks are below the station and not visible from the platforms.",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": true,
        "has_street_entrance": false,
        "subway_division": 26
    },
    {
        "id": 110,
        "borough": "Staten Island",
        "construction_type": "Open Cut / Grade Level",
        "mezzanine_configuration": "Elevated Mezzanine",
        "platform_type": "Sides",
        "package": "TBD",
        "lines": [],
        "task_id": 2,
        "station_name": "Richmond Valley",
        "station_id": "SI1",
        "latitude": 40.5196,
        "longitude": -74.2293,
        "is_historic_landmark": false,
        "area_square_feet": 10665.0,
        "number_of_platforms": 2,
        "number_of_local_tracks": 2,
        "number_of_express_tracks": 0,
        "track_comments": "",
        "has_building_entrance": false,
        "has_canopy_entrance": false,
        "has_elevated_entrance": true,
        "has_street_entrance": false,
        "subway_division": 28
    }
];